### ISSUE TITLE
Unable to utilize Early Bound generated entities with DLaBPluginBase

### ISSUE THREAD

**Issue by jj-bdo** [daryllabar/DLaB.Xrm#51]
I've used the DLaB entity generator to add Connection, Account, Contact, as well as a few custom entities. They are added to my plugin project and are available for use in the plugin code. However when trying to use .ToEntity<Connection>() or ToEntityList<Connection>() I receive "Unable to cast object of type 'Microsoft.Xrm.Sdk.Entity' to type 'NAMESPACEHERE.Connection'".

I tried looking through the initialization of the org service, in the past I've had to use an orgproxy and call EnableProxyTypes(). I can't seem to find where to do that here in a plugin.

**Comment by daryllabar** [comment]
I'm not familiar with ToEntityList(). Is that new?  Regardless you shouldn't be getting a cast exception.  The ToEntity Implementation would take the Attributes collection and shove it into a new instance of your custom type.  You do have the ProxyTypeAssembly attribute, correct?  https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.client.proxytypesassemblyattribute?view=dataverse-sdk-latest
